import json
import logging
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

logger = logging.getLogger(__name__)


# Constants

DEFAULT_SEGMENTS_PER_CHUNK = 15


# Transcript Loader

def load_transcript(transcript_path):
    """
    Load transcript JSON generated by the transcription pipeline.
    """

    transcript_path = Path(transcript_path)

    if not transcript_path.exists():
        raise FileNotFoundError(
            f"Transcript file not found: {transcript_path}"
        )

    with open(transcript_path, "r", encoding="utf-8") as f:
        return json.load(f)



# Chunk Creator


def create_chunks(
    segments,
    segments_per_chunk=DEFAULT_SEGMENTS_PER_CHUNK
):
    """
    Convert transcript segments into chunk objects.
    """

    chunks = []

    for chunk_id, start_idx in enumerate(
        range(
            0,
            len(segments),
            segments_per_chunk
        )
    ):

        group = segments[
            start_idx:
            start_idx + segments_per_chunk
        ]

        if not group:
            continue

        chunk = {
            "chunk_id": chunk_id,

            "start": group[0]["start"],
            "end": group[-1]["end"],

            "duration": (
                group[-1]["end"]
                - group[0]["start"]
            ),

            "segment_start": group[0]["segment_id"],
            "segment_end": group[-1]["segment_id"],

            "segment_ids": [
                seg["segment_id"]
                for seg in group
            ],

            "num_segments": len(group),

            "text": "\n\n".join(
                seg["text"].strip()
                for seg in group
            )
        }

        chunks.append(chunk)

    return chunks


# Chunk Saver


def save_chunks(
    chunks,
    source_metadata,
    output_path
):
    """
    Save chunked transcript to JSON.
    """

    output_data = {
        "source": source_metadata,
        "chunks": chunks
    }

    output_path = Path(output_path)

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        output_path,
        "w",
        encoding="utf-8"
    ) as f:
        json.dump(
            output_data,
            f,
            indent=4,
            ensure_ascii=False
        )

    logger.info(
        f"Chunks saved to: {output_path}"
    )

# Public API


def chunk_transcript(
    transcript_json_path,
    output_dir="outputs",
    segments_per_chunk=DEFAULT_SEGMENTS_PER_CHUNK
):
    """
    Main entry point for transcript chunking.
    """

    transcript = load_transcript(
        transcript_json_path
    )

    source = transcript["source"]
    segments = transcript["segments"]

    logger.info(
        f"Loaded {len(segments)} segments."
    )

    chunks = create_chunks(
        segments,
        segments_per_chunk
    )

    logger.info(
        f"Generated {len(chunks)} chunks."
    )

    transcript_path = Path(
        transcript_json_path
    )

    output_dir = Path(output_dir)

    chunk_dir = output_dir / "chunks"

    chunk_path = (
        chunk_dir /
        f"{transcript_path.stem}_chunks.json"
    )

    save_chunks(
        chunks,
        source,
        chunk_path
    )

    return {
        "chunks_path": str(chunk_path),
        "num_chunks": len(chunks),
        "segments_processed": len(segments)
    }


# Example Usage


if __name__ == "__main__":

    result = chunk_transcript(
        "outputs/transcripts/ciHThtTVNto.json"
    )

    print(json.dumps(
        result,
        indent=4
    ))