import json
import logging
from pathlib import Path

from config import (
    DEFAULT_SEGMENTS_PER_CHUNK,
    TARGET_MAX_CHUNKS,
    MAX_SEGMENTS_PER_CHUNK,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

logger = logging.getLogger(__name__)


# Constants
# The canonical default lives in config.py (single source of truth). The
# previous local constant of 5 drifted from config's 15, silently tripling the
# number of extraction LLM calls per lecture. See ROADMAP P1.1.


# Transcript Loader

def load_transcript(transcript_path):
    """
    Load transcript JSON generated by the transcription pipeline.
    """

    transcript_path = Path(transcript_path)

    if not transcript_path.exists():
        raise FileNotFoundError(
            f"Transcript file not found: {transcript_path}"
        )

    with open(transcript_path, "r", encoding="utf-8") as f:
        return json.load(f)



# Chunk Creator


def adaptive_segments_per_chunk(num_segments: int) -> int:
    """
    Pick the chunk size for a transcript of `num_segments` segments (P1.8).

    Short lectures keep the default 15-segment chunks. Long lectures grow the
    chunk size so the total number of chunks (and hence extraction LLM calls)
    stays bounded: spc = ceil(segments / TARGET_MAX_CHUNKS), clamped to
    MAX_SEGMENTS_PER_CHUNK. Pure function of segment count — mirrors the
    estimator in backend/estimator.py so the pre-flight estimate and the actual
    pipeline never drift.
    """
    if num_segments <= TARGET_MAX_CHUNKS * DEFAULT_SEGMENTS_PER_CHUNK:
        return DEFAULT_SEGMENTS_PER_CHUNK
    import math

    return min(
        math.ceil(num_segments / TARGET_MAX_CHUNKS),
        MAX_SEGMENTS_PER_CHUNK,
    )


def create_chunks(
    segments,
    segments_per_chunk=DEFAULT_SEGMENTS_PER_CHUNK
):
    """
    Convert transcript segments into chunk objects.
    """

    chunks = []

    for chunk_id, start_idx in enumerate(
        range(
            0,
            len(segments),
            segments_per_chunk
        )
    ):

        group = segments[
            start_idx:
            start_idx + segments_per_chunk
        ]

        if not group:
            continue

        chunk = {
            "chunk_id": chunk_id,

            "start": group[0]["start"],
            "end": group[-1]["end"],

            "duration": (
                group[-1]["end"]
                - group[0]["start"]
            ),

            "segment_start": group[0]["segment_id"],
            "segment_end": group[-1]["segment_id"],

            "segment_ids": [
                seg["segment_id"]
                for seg in group
            ],

            "num_segments": len(group),

            "text": "\n\n".join(
                seg["text"].strip()
                for seg in group
            )
        }

        chunks.append(chunk)

    return chunks


# Chunk Saver


def save_chunks(
    chunks,
    source_metadata,
    output_path
):
    """
    Save chunked transcript to JSON.
    """

    output_data = {
        "source": source_metadata,
        "chunks": chunks
    }

    output_path = Path(output_path)

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        output_path,
        "w",
        encoding="utf-8"
    ) as f:
        json.dump(
            output_data,
            f,
            indent=4,
            ensure_ascii=False
        )

    logger.info(
        f"Chunks saved to: {output_path}"
    )

# Public API


def chunk_transcript(
    transcript_json_path,
    output_dir,
    segments_per_chunk=None
):
    """
    Main entry point for transcript chunking.

    segments_per_chunk: explicit chunk size; None (default) → adaptive chunk
    sizing from the transcript's segment count (P1.8).
    """

    transcript = load_transcript(
        transcript_json_path
    )

    source = transcript["source"]
    segments = transcript["segments"]

    logger.info(
        f"Loaded {len(segments)} segments."
    )

    if segments_per_chunk is None:
        segments_per_chunk = adaptive_segments_per_chunk(
            len(segments)
        )
        logger.info(
            f"Adaptive chunk size: {segments_per_chunk} "
            f"segments/chunk (target ≤ {TARGET_MAX_CHUNKS} chunks)."
        )

    chunks = create_chunks(
        segments,
        segments_per_chunk
    )

    logger.info(
        f"Generated {len(chunks)} chunks."
    )

    transcript_path = Path(
        transcript_json_path
    )

    output_dir = Path(output_dir)

    chunk_dir = output_dir / "chunks"

    chunk_path = (
        chunk_dir /
        f"{transcript_path.stem}_chunks.json"
    )

    save_chunks(
        chunks,
        source,
        chunk_path
    )

    return {
        "chunks_path": str(chunk_path),
        "num_chunks": len(chunks),
        "segments_processed": len(segments),
        "segments_per_chunk": segments_per_chunk,
    }


# Example Usage


if __name__ == "__main__":

    result = chunk_transcript(
        "outputs/transcripts/ciHThtTVNto.json",
        "outputs"
    )

    print(json.dumps(
        result,
        indent=4
    ))